spring:
  profiles:
    active: development

  data:
    mongodb:
      database: mydb
      #username: MongoDB
      #password: root
      #port: 27017
      #host: 127.0.0.1
  jmx:
    enabled: true

logging:
  level:
    org:
      springframework: info

server:
  port: 8080