server:
  port: 7002
  tomcat:
    max-http-header-size: 30M

app:
  fileServerUrl: http://localhost:7001
  fileDirectory: /home/fileStorage/
  #fileServerUrl: http://127.0.0.1:7001
  #fileDirectory: C:\fileStorage\

spring:
  application:
    name: library-microservice
  #cloud:
  #  config:
  #    fail-fast: true
  #    uri: http://127.0.0.1:5000
  #profiles:
  #  active: development
  #datasource:
  #  url: jdbc://127.0.0.1:27017/mydb
  #  #driver-class-name: mongodb.jdbc.MongoDriver
  #  driver-class-name:
  data:
    mongodb:
      profiles:
        active: development

      database: mydb
#      uri: mongodb://dgvozdev:2mL3VmSLfzMngDBPassword@0.0.0.0:27017
#      username: dgvozdev
#      password: 2mL3VmSLfzMngDBPassword
#      authentication-database: mydb
#      host: 0.0.0.0
      uri: mongodb://127.0.0.1:27017/mydb
      host: 127.0.0.1
      port: 27017

  #thymeleaf:
  #  prefix: classpath:/templates
  #  suffix: .html
    #enabled: false

  #spring.data.mongodb.host=localhost
  #spring.data.mongodb.port=27017
  #spring.data.mongodb.database=app1

  jmx:
    enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

management:
  endpoints:
    web:
      exposure:
        include=*

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8001/eureka
#    register-with-eureka: true
#    fetch-registry: true
#  server:
#    eviction-interval-timer-in-ms: 15000
#  instance:
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
#    instance-id: ${spring.application.name}:${server.port}
#    prefer-ip-address: true

#use: feign

#hystrix:
#  command:
#    findByBookId:
#      metrics:
#        rollingStats:
#          timeInMilliseconds: 15000
#      circuitBreaker:
#        requestVolumeThreshold: 10
#        errorThresholdPercentage: 50
#        sleepWindowInMilliseconds: 6000
#    findFileByBookIdBreaker:
#      metrics:
#        rollingStats:
#          timeInMilliseconds: 15000
#        circuitBreaker:
#          requestVolumeThreshold: 10
#          errorThresholdPercentage: 50
#          sleepWindowInMilliseconds: 6000
#  execution:
#    isolation:
#      thread:
#        timeoutInMilliseconds: 3000

logging:
  level:
    org:
      springframework: info