spring:
  profiles:
    active: development

  data:
    mongodb:
      database: mydb
  jmx:
    enabled: true

logging:
  level:
    org:
      springframework: info

server:
  port: 8080

app:
  fileServerUrl: http://127.0.0.1:8081