spring:
  profiles:
    active: development
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  data:
    mongodb:
      database: mydb
#      username: MongoDB
#      password: root
#      port: 27017
#      host: localhost
#      authentication-database: admin
  jmx:
    enabled: true
---
logging:
  level:
    org:
      springframework: info