version: "3"
services:
  api:
    image: api
    ports:
      - "8081:8080"
    build: .
    links:
      - mdb
    depends_on:
      - mdb
    #environment:
    #  - NODE_ENV=development
    #  - FOO=bar
    #entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"

  mdb:
    image: mdb
    container_name: "mdb"
    ports:
      - "27018:27018"
    command: --smallfiles
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27018
    #volumes:
    #  - ./data/db:/data/db
    #command: mongod --smallfiles --logpath=/dev/null
