version: "3"
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: ['NET_ADMIN','NET_RAW']
    restart: on-failure

  file-rest-api:
    build: .
    container_name: file-rest-api
    image: file-rest-api
    ports:
      - "8181:8080"
    links:
      - mongodbfs
    environment:
      database: libraryFiles
      port: 27018
      host: localhost

  mongodbfs:
    container_name: mongodbfs
    image: mongo:4.0.4
    ports:
      - "27018:27017"
    volumes:
      - my_dbdata:/data/db

volumes:
  my_dbdata:

  #api:
    #image: api
    #ports:
    #  - 8181:8080
    #build: .
    #links:
    #  - mdb
    #depends_on:
    #  - mdb
    #environment:
    #  - NODE_ENV=development
    #  - FOO=bar
    #entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"

  #mdb:
    #  image: mongo:4.0.4
    #  container_name: "mdb"
    #  ports:
    #    - "27017:27017"
    #  command: --smallfiles

