version: "2"
services:
  file-rest-api:
    image: file-rest-api
    container_name: "file-rest-api"
    build:
      context: .
      dockerfile: file-server/Dockerfile
    networks:
      - myapp
    depends_on:
      - mongo
    ports:
      - "8181:8080"
  library:
    image: library
    container_name: "library"
    build:
      context: .
      dockerfile: library/Dockerfile
    networks:
      - myapp
    depends_on:
      - mongo
    ports:
      - "8182:8080"
  mongo:
    image: mongo:4.0.4
    container_name: "mongo"
    ports:
      - '27018:27017'
    networks:
      - myapp
networks:
  myapp:
    driver: bridge