version: "3"
services:
  file-rest-api:
    image: file-rest-api
    container_name: "file-rest-api"
    build:
      context: .
      dockerfile: file-server/Dockerfile
    networks:
      - my-network
    ports:
      - "8181:8080"
    #links:
    #  - mongo
    #environment:
    #  database: mydb
    #  port: 27017
    #  uri: mongodb://mongo:27017/mydb
  library:
    image: library
    container_name: "library"
    build:
      context: .
      dockerfile: library/Dockerfile
    networks:
      - my-network
    ports:
      - "8182:8080"
    #links:
    #  - mongo
    #environment:
    #  database: mydb
    #  port: 27017
    #  uri: mongodb://mongo:27017/mydb
  mongo:
    image: mongo:4.0.4
    container_name: "mongodb"
    ports:
      - "27018:27017"
    #environment:
    #  database: mydb
    #  port: 27017
    #  uri: mongodb://127.0.0.1:27017
    volumes:
      - my_dbdata:/data/db
networks:
  my-network: {}
volumes:
  my_dbdata: