version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    #volumes:
    #  - my_data: /data/db

 # file-rest-api:
 #   image: file-rest-api
 #   container_name: file-rest-api
 #   build:
 #     context: .
 #     dockerfile: file-server/Dockerfile
 #   depends_on:
 #     - mongodb
 #   ports:
 #     - 7001:7001
    #  - 8081:8080
 #   expose:
 #    - 7001
 #   links:
 #     - mongodb

  library:
    image: library
    container_name: library
    build:
      context: .
      dockerfile: library/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 7002:7002
      #- 8080:8080
    expose:
      - 7002
    links:
      - mongodb

#  eureka-server:
#    image: eureka-server
#    container_name: eureka-server
#    build:
#      context: .
#      dockerfile: eureka/Dockerfile
#    depends_on:
#      - mongodb
#    ports:
#      - 8001:8001
#      - 8002:8002
#      #- 8001:8002
#    expose:
#      - 8001
#      - 8002
#    links:
#      - mongodb

#  hystrix-dashboard:
#    image: hystrix-dashboard
#    container_name: hystrix-dashboard
#    build:
#      context: .
#      dockerfile: hystrix-dashboard/Dockerfile
#    depends_on:
#      - mongodb
#    ports:
#      - 8788:8788
#    expose:
#      - 8788
#      #- 8788:8002
#    links:
#      - mongodb
#volumes:
#  my_data: