version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    #volumes:
    #  - my_data: /data/db

  file-rest-api:
    image: file-rest-api
    container_name: file-rest-api
    build:
      context: .
      dockerfile: file-server/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 8081:8080
    links:
      - mongodb

  library:
    image: library
    container_name: library
    build:
      context: .
      dockerfile: library/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    links:
      - mongodb
#volumes:
#  my_data: