management:
  endpoints:
    web:
      exposure:
        include: health,metrics,logfile
  endpoint:
    health:
      show-details: always
  health:
    database:
      enabled: false
    mongo:
      enabled: true
---
spring:
  data:
    mongodb:
      database: mydb
      #username: MongoDB
      #password: root
      #port: 27017
      #host: localhost
      #authentication-database: admin
  profiles:
    active: development
    #active: test
  jmx:
    enabled: true
---
logging:
  file:
    path: "/home-work-16.log"
  level:
    org:
      springframework: info