INSERT INTO STATUSES (ID, `NAME`) VALUES (1, 'active');
INSERT INTO STATUSES (ID, `NAME`) VALUES (0, 'inactive');

INSERT INTO AUTHORS (ID, FIRSTNAME, SECONDNAME, THIRDNAME, BIRTH_DATE)
VALUES (1, 'Ник', 'Перумов', '', CURRENT_TIMESTAMP);
INSERT INTO AUTHORS (ID, FIRSTNAME, SECONDNAME, THIRDNAME, BIRTH_DATE)
VALUES (2, 'Даниэль', 'Дефо', '', CURRENT_TIMESTAMP);
INSERT INTO AUTHORS (ID, FIRSTNAME, SECONDNAME, THIRDNAME, BIRTH_DATE)
VALUES (3, 'Михаил', 'Афанасьевич', 'Булгаков', CURRENT_TIMESTAMP);

INSERT INTO GENRES (ID, `NAME`) VALUES (1, 'Фэнтези');
INSERT INTO GENRES (ID, `NAME`) VALUES (2, 'Приключения');
INSERT INTO GENRES (ID, `NAME`) VALUES (3, 'Роман');

INSERT INTO COMMENTS (ID, BOOK_ID, COMMENT, CREATE_DATE) VALUES (1, 1, 'Хорошая книга', CURRENT_TIMESTAMP);
INSERT INTO COMMENTS (ID, BOOK_ID, COMMENT, CREATE_DATE) VALUES (2, 2, 'Интересная книга', CURRENT_TIMESTAMP);

INSERT INTO BOOKS (ID, `NAME`, CREATE_DATE, DESCRIPTION, `IMAGE`, GENRES, STATUS, AUTHORS)
VALUES (1, 'Кольцо тьмы', CURRENT_TIMESTAMP, 'Магия, миры, приключения...', NULL, 1, 1, 1);
INSERT INTO BOOKS (ID, `NAME`, CREATE_DATE, DESCRIPTION, `IMAGE`, GENRES, STATUS, AUTHORS)
VALUES (2, 'Робинзон Крузо', CURRENT_TIMESTAMP, 'Как выжить на необитаемом острове', NULL, 1, 1, 1);

INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (1, 3);
INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (2, 2);
INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (3, 1);

INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTHOR_ID) VALUES (1, 3);
INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTHOR_ID) VALUES (2, 2);
INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTHOR_ID) VALUES (3, 1);

INSERT INTO USERS(USERNAME,PASSWORD) VALUES ('admin','password');
INSERT INTO USERS(USERNAME,PASSWORD) VALUES ('user','password');

INSERT INTO ROLES(ROLE,DESCRIPTION) VALUES ('ROLE_ADMIN','Администратор');
INSERT INTO ROLES(ROLE,DESCRIPTION) VALUES ('ROLE_USER','Пользователь');

INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('user', 'ROLE_USER');