DROP TABLE IF EXISTS STATUSES;
CREATE TABLE STATUSES(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255),
  SECONDNAME VARCHAR(255),
  THIRDNAME VARCHAR(255),
  BIRTH_DATE TIMESTAMP,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  BOOK_ID INT,
  COMMENT VARCHAR(255),
  CREATE_DATE TIMESTAMP,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  CREATE_DATE TIMESTAMP,
  DESCRIPTION VARCHAR(255),
  IMAGE VARBINARY(MAX),
  GENRE INT,
  STATUS INT,
  AUTHOR INT,
  COMMENT INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (GENRE) REFERENCES GENRES (ID),
  FOREIGN KEY (STATUS) REFERENCES STATUSES (ID),
  FOREIGN KEY (AUTHOR) REFERENCES AUTHORS (ID),
  FOREIGN KEY (COMMENT) REFERENCES COMMENTS (ID)
);