DROP TABLE IF EXISTS STATUSES;
CREATE TABLE STATUSES(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255),
  SECONDNAME VARCHAR(255),
  THIRDNAME VARCHAR(255),
  BIRTH_DATE TIMESTAMP,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  BOOK_ID INT,
  COMMENT VARCHAR(255),
  CREATE_DATE TIMESTAMP,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  CREATE_DATE TIMESTAMP,
  DESCRIPTION VARCHAR(255),
  IMAGE VARBINARY(MAX),
  GENRES INT,
  STATUS INT,
  AUTHORS INT,
  COMMENTS INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (GENRES) REFERENCES GENRES (ID),
  FOREIGN KEY (STATUS) REFERENCES STATUSES (ID),
  FOREIGN KEY (AUTHORS) REFERENCES AUTHORS (ID),
  FOREIGN KEY (COMMENTS) REFERENCES COMMENTS (ID)
);

DROP TABLE IF EXISTS BOOK_GENRE;
CREATE TABLE BOOK_GENRE(
  BOOK_ID BIGINT NOT NULL,
  GENRE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE BOOK_AUTHOR(
  BOOK_ID BIGINT NOT NULL,
  AUTHOR_ID BIGINT NOT NULL
);