spring:
  profiles:
    active: development
  data:
    mongodb:
      database: libraryFiles
#      username: MongoDB
#      password: root
#      port: 27017
#      host: localhost
#      authentication-database: admin
#  jmx:
#    enabled: true
  fileDirectory: C:\fileStorage\

---
logging:
  level:
    org:
      springframework: info