server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5
    registry-sync-retries: 3
    max-threads-for-peer-replication: 0